INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 471);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('1984', 'George Orwell', 328);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('El principito', 'Antoine de Saint-Exupéry', 96);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', 1032);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Orgullo y prejuicio', 'Jane Austen', 432);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('El Hobbit', 'J.R.R. Tolkien', 310);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Rayuela', 'Julio Cortázar', 600);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Fahrenheit 451', 'Ray Bradbury', 158);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Un mundo feliz', 'Aldous Huxley', 256);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Crónica de una muerte anunciada', 'Gabriel García Márquez', 150);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('La sombra del viento', 'Carlos Ruiz Zafón', 576);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('El alquimista', 'Paulo Coelho', 192);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Los pilares de la Tierra', 'Ken Follett', 1016);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Drácula', 'Bram Stoker', 418);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Frankenstein', 'Mary Shelley', 280);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('El retrato de Dorian Gray', 'Oscar Wilde', 250);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Moby Dick', 'Herman Melville', 820);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Pedro Páramo', 'Juan Rulfo', 132);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Ensayo sobre la ceguera', 'José Saramago', 320);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('El amor en los tiempos del cólera', 'Gabriel García Márquez', 496);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Ficciones', 'Jorge Luis Borges', 176);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('El guardián entre el centeno', 'J.D. Salinger', 277);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('La metamorfosis', 'Franz Kafka', 128);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('El resplandor', 'Stephen King', 600);
INSERT INTO libros (titulo, autor, numero_paginas) VALUES ('Crimen y castigo', 'Fiódor Dostoyevski', 500);